### ISSUE TITLE
Warning: GMP or MPIR library not found; Unable to find vcvarsall.bat

### ISSUE THREAD

**Issue by sebie** [keybase/python-triplesec#7]
When I installed TripleSec via Pip I get the following error:

```
warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.

error: Unable to find vcvarsall.bat

----------------------------------------
Cleaning up...
Command C:\Python34\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\USERNAME\\AppData\\Local\\Temp\\pip_build_USERNAME\\pycrypto\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\USERNAME\AppData\Local\Temp\pip-12glkwre-record\install-record.txt --single-version-externally-managed --compile failed with error code 1 in C:\Users\USERNAME\AppData\Local\Temp\pip_build_USERNAME\pycrypto
Storing debug log for failure in C:\Users\USERNAME\pip\pip.log
```

The full error is pasted [here.](http://paste.ubuntu.com/8845317/)

And when I try to type "TripleSec" into an administrator CLI I get this:

```
Traceback (most recent call last):
  File "C:\Python34\Scripts\triplesec-script.py", line 5 in <module> from pkg_resources import load_entry_point
  File "C:\Python34\lib\site-packages\pkg_resources.py", line 2697 in <module> working_set.require(_requires_)
  File "C:\Python34\lib\site-packages\pkg_resources.py", line 669 in require needed = self.resolve(parse_requirements(requirements))
  File "C:\Python34\lib\site-packages\pkg_resources.py", line 572 in resolve raise DistrobutionNotFound(req)
pkg_resources.DistributionNotFound: salsa20
```

**Comment by heronhaye** [comment]
Should be better now with pycryptodome. Try it out and make another issue if you still have problems. Thanks!
